config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: "home#index"

   resources :categories
   resources :carts do
    post "/update_cart", to: "carts#update_cart"
   end
   resources :products do
    get "/add_to_cart", to: "products#add_to_cart"
   end
  resources :orders do
    post 'create_order',to: 'orders#create_order', on: :collection
    get  'pay',to: 'orders#pay',  on: :collection
 end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    if user.super_admin?
      can :manage, :all
    else
      
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items, dependent: :destroy
	has_many :products, through: :cart_items
	
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product	
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :name, presence: true
	validates_uniqueness_of :name
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :product
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :image
	belongs_to :category, optional: true
	belongs_to :user
	has_many :cart_items, dependent: :destroy
	has_many :carts, through: :cart_items 
	has_many :order_items, dependent: :destroy
	has_many :orders, through: :order_items
	validates :name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :cart, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_user.cart
    @cart_item = current_user.cart.cart_items if @cart.present?
  end

  def destroy
    @cart_item = current_user.cart.cart_items.find_by(id: params[:id])
    if @cart_item.present?
       @cart_item.destroy
    end
    redirect_to carts_path, notice: "Succefully remove cart_item"
  end
 def update_cart
    cart_item = CartItem.find_by(id: params[:cart_id])
    product_price = cart_item.product.price  
    up_quantity = cart_item.update(product_quantity: params[:product_quantity].to_i, total_price: params[:product_quantity].
      to_i * product_price)
    redirect_to carts_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	 def index
    @category = Category.all
	 end

	 def show
	 		@category = Category.find(params[:id])
	 end

	def create
	  @category = Category.new(category_params)
	  if  @category.save
	  	redirect_to root_path, notice: "Succefully created category"
	  else
	  	render 'new'
	  end
	 end

  def edit
    @category = Category.find(params[:id])
  end

	def update
    @category = Category.find(params[:id])
 
	  if @category.update(category_params)
	    redirect_to categories_path,  notice: "Succefully update category"
	   else
	    render 'edit'
	  end
  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy
 
    redirect_to categories_path, notice: "Succefully destroy category"
  end


	def category_params
		params.require(:category).permit(:name)	
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@product = Product.all
		@product =Product.where('name like ?',"#{params["name"]}%")
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
skip_before_action :verify_authenticity_token
  Razorpay.setup('rzp_test_wrYixxsZmgVEj5', 'BZv1rukXURb10VLLX39XfHuk')
	def create_order
		cart = current_user.cart
		if cart.present? and cart.cart_items.present?
	  	price = cart.total_price * 100
			@order = current_user.orders.new(total_price: price.to_i, total_quantity: cart.total_quantity)
		   cart.cart_items.each do |order_item|
          @order_item = @order.order_items.new(product_id: order_item.product_id, total_price: order_item.total_price, product_quantity: order_item.product_quantity)
              @order_item.save
       end   
			if @order.save
        cart.cart_items.delete_all
         order = Razorpay::Order.create(amount: price.to_i, currency: 'INR', receipt: 'TEST')
               @order.update(razorpay_order_id: order.id)
          redirect_to order_pay_path(order_id: @order.id)
      end
		end
  end

	def pay
	    @order = Order.find_by(id: params[:order_id])
	 end


 	def index
 		@order_items = current_user.order_items
     @orders = current_user.orders
   end

  def show
    @order_item = OrderItem.find(params[:id])
  end

	def update_order
	      @order = Order.find_by(id: params[:id])
	      if @order.present?
	         payment_response = {
	         	razorpay_order_id: params[:razorpay_order_id], 
	         	razorpay_payment_id: params[:razorpay_payment_id],
	         	 razorpay_signature: params[:razorpay_signature] }

	         verify_result = Razorpay::Utility.verify_payment_signature(payment_response)
	         if verify_result
	            @order.update(razorpay_payment_id: params[:razorpay_payment_id])   
	            redirect_to orders_path
	         else
	            flash[:error] = "something went wrong!!!"
	         end
	      end
	   end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def create
		@product = current_user.products.new(product_params)
			 if @product.save
			 	redirect_to root_path, notice: "Succefully created product"
			 else
			 	render 'new'
			 end
	end
 def show
 		@product = Product.find(params[:id])
 end

 def edit
    @product = Product.find(params[:id])
  end

	def update
    @product = Product.find(params[:id])
		
 
	  if @product.update(product_params)
	    redirect_to category_path, notice: "Succefully update product"
	   else
	    render 'edit'
	  end
	 end

	def destroy
    @product = Product.find(params[:id])
    @product.destroy
 
    redirect_to categories_path, notice: "Succefully destroy product"
  end
  
  def add_to_cart
    cart = Cart.find_or_create_by(user_id: current_user.id)
     if cart.present?
      product = Product.find_by(id: params[:product_id])
      if cart.cart_items.find_by(product_id: product.id).present?
        redirect_to product_path(product.id), notice: "Product is already in cart_items"
      else
        cart_item = cart.cart_items.new(product_id: product.id, total_price: product.price, product_quantity: 1)
        debugger
        if cart_item.save
            redirect_to carts_path
         else  
        end
      end
   end
 end
	def product_params
		params.require(:product).permit(:name, :price, :category_id, :image)		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<h1>Cart_items</h1>
<% if @cart.present? %>
 <div class="row">
   <% if @cart_item.present? %>
      <% @cart_item.each do |cart| %>  
         <div class="column">
             <%if cart.product.image.present?%>
                 <%= image_tag cart.product.image, :size => "150x150" %></div></br>
              <%end%>
         </div>
         
          <div class="column">
            <h4>price = <%= cart.total_price%></h4>
            <h4>Name = <%= cart.product.name%></h4>
             <h4>Quantity = <%= cart.product_quantity%></h4>
            <h4><%= link_to "Remove", cart_path(cart.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></h4>
          </div>
        <%= form_with url: cart_update_cart_path(cart_id: cart), method: "post" do |form| %>
          <h4> Quantity = <%= form.number_field :product_quantity, :value => cart.product_quantity %><br></h4>
           <%= form.submit %>
        <% end %>
      <%end %> 
       <h4>Total_price = <%= @cart.cart_items.pluck(:total_price).sum%></h4>
       <h4>Quantity = <%= @cart.cart_items.pluck(:total_quantity).count%></h4>
       <%= form_with url: create_order_orders_path, method: "post" do |f|%>
       <%= f.submit "Buy"%><br/><br/>
       <%end%>
   <%end %>
<%end %>

app/views/categories/_form.html.erb
<%= form_with scope: :category, url: categories_path, local: true do |form| %> 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<%= form_with model: @category, local: true do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :name %>
  </p>
 

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/categories/index.html.erb
<h1>All category</h1>
<%= link_to 'Cart_item',carts_path %></br>
 <% @category.each do |category| %>
    <tr>
      <td><%= category.name %></td>
    </tr>
      <td><%= link_to 'Show', category_path(category) %></td>
      <%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td></br>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
 <% @product = @category.products%>
 <%if @product.present?%>
   <% @product.each do |product| %>
      <%= link_to (image_tag product.image, size: "150x160"),product_path(product)%></a>
      <td><%= link_to 'Edit', edit_product_path(product)%></td>

      <td><%= link_to 'Destroy', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td></br>
      </br>
     <% end %>
   <% else %>
  < h1>No product available in this category </h1>
 <%end%>

app/views/home/index.html.erb
 <br>
<body class="bg-dark">
      <% if current_user&.role == "super_admin"%>
  <div class="container" style="max-width: 45%;">
    <div class="card text-center" >
      <div class="card-body ">
       <h5 class=" text-center">Admin Pannel</h5><br>
       <h6 class="card-subtitle mb-2 text-muted">Login super admin</h6>
       <button class="btn btn-outline-primary"><%= link_to 'Create_category',new_category_path %></button>
       <button class="btn btn-outline-primary"><%= link_to 'Create_products',new_product_path %></button></br> <button class="btn btn-outline-primary margin_space"><%= link_to 'Show_category',categories_path %>
      </button>
   </div>
 </div>
</div>
      <%else%>
    </br><div class="container ">
     <div class="card text-center" >
     <h5 class=" text-center">All products</h5><br>
  <% @product.each_slice(4) do |products| %>
    <div class="row">
      <% products.each do |product| %> 
        <div class="col-sm-3"></br>
         <div class="text-black zoom hover p-3" style="width: 18rem">
           <%= link_to (image_tag product.image, size: "240x180"),product_path(product)%>
            <h4>Name = <%= product.name%></h4>
         </div>
       </div>
      <% end %>
    </div>
   <% end %>
  </div>    
 </div>
 <%end%>

app/views/orders/index.html.erb
</br><div class="container ">
     <div class="card text-center" >
     <h5 class=" text-center">All orders</h5><br>
  <% @order_items.each_slice(4) do |order_items| %>
    <div class="row">
      <% order_items.each do |order_item| %> 
        <div class="col-sm-3"></br>
         <div class="text-black zoom hover p-3" style="width: 18rem">
         <%= link_to(image_tag(order_item.product.image, size: "240x180"),order_path(order_item))%><br> 
            <h4>Name = <%= order_item.product.name%></h4>
         </div>
       </div>
      <% end %>
    </div>
  <% end %>
  </div>    
</div>
 

app/views/orders/pay.html.erb
<h3>pay for orders</h3>
 <br>
   <body class="bg-dark">
  <div class="container" style="max-width: 45%;">
    <div class="card text-center" >
     <div class="card-body ">
      <h5 class=" text-center">Please pay for order </h5><br>
      <button id = "rzp-button1" class="btn btn-outline-secondary ">Pay Now</button>
      <script src = "https://checkout.razorpay.com/v1/checkout.js"></script>
      <script>
      var options = {
        "key": "rzp_test_wrYixxsZmgVEj5",
        "order_id": "<%= @order.razorpay_order_id %>",
        "id": "<%= @order.id %>",
        "name": "Acme Corp.",
        "currency": "INR",
        "image": "/your_logo.jpg",
        "callback_url": "/orders/<%= @order.id%>/update_order",
        "prefill": {
         "amount": "<%= @order.total_price %>"  
        },
        "theme": {
          "color": "#F37254"
        }
      };
        var rzp1 = new Razorpay(options);
        document.getElementById('rzp-button1').onclick = function(e) {
          rzp1.open();
          e.preventDefault();
        }
    </script>
  </div>
 </div>
</body>


    

app/views/orders/show.html.erb
 <br>
   <body class="bg-dark">
  <div class="container" style="max-width: 45%;">
    <div class="card text-center" >
  <h2>Detail of my order</h2>
  <%if @order_item.product.image.present?%>
    <%= link_to product_path(@order_item.product_id) do%>
      <%= image_tag @order_item.product.image %></a>
    <%end%>
  <% end %>
<h3>price of product = <%= @order_item.total_price %> </h3>
<h3>Quantity of prduct = <%= @order_item.product_quantity %> </h3>
</div>
</div>
</body>

app/views/products/edit.html.erb
<%= form_with model: @product, local: true do |form| %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :name %>
  </p>
 <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %></br>
  </div>
   <%= form.label :image %><br>
    <%= form.file_field :image, accept: 'image/png, image/gif, image/jpeg, image/jpg'%></br>
  </div>
    <%= form.label :category_id %><br>
    <%= form.select :category_id, options_for_select(Category.all.map{|b| [b.name, b.id]}) %><br>
   </div>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/products/new.html.erb
<%= form_with scope: :product, url: products_path, local: true do |form| %> 
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %></br>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %></br>
  </div>
    <%= form.label :image %><br>
    <%= form.file_field :image, accept: 'image/png, image/gif, image/jpeg, image/jpg'%></br>
  </div>
    <%= form.label :category_id %><br>
    <%= form.select :category_id, options_for_select(Category.all.map{|b| [b.name, b.id]}) %><br>
   </div
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/products/show.html.erb
<h1>Products detail</h1>
  <%= image_tag @product.image, size: "150x160" %></a></br>
  <h5>Category_name = <%= @product.name%> </h5>
  <h5>Product price = <%= @product.price%></h5>
  <%= link_to 'Add', product_add_to_cart_path(@product.id) %>
</br>